name: Killstreaks
author: LimeGlass
description: Add Killstreaks to Minecraft.
version: 1.0.0
main: me.limeglass.killstreaks.Killstraks
commands:
  killstreaks:
    description: Killstreaks main command.
    usage: /killstreaks
    permission: killstreaks.use
permissions:
  killstreaks.*:
    description: Gives access to all Killstreaks commands.
    children:
      killstreaks.admin: true
  killstreaks.admin:
    description: Gives access to setup killstreaks and other components.
    default: op